const evidence=[
{id:'price',type:'Сторінка товару',title:'Знижка 45% «лише сьогодні»',preview:'5 000 → 2 750 грн · таймер',visual:'КАРТКА ТОВАРУ\n\nНавушники Pro X\nСтара ціна: 5 000 грн\nНова ціна: 2 750 грн\n\n«ЛІКВІДАЦІЯ СКЛАДУ — ЛИШЕ СЬОГОДНІ»\nТаймер: 00:17:42',copy:'Надто велика знижка разом із тиском часу не доводить шахрайство сама по собі, але є сильним сигналом для додаткової перевірки.',key:true,icon:'-45%'},
{id:'photo',type:'Фото товару',title:'Якісні фотографії навушників',preview:'Білий фон · кілька ракурсів',visual:'ФОТОГАЛЕРЕЯ\n\n5 професійних фото товару на білому фоні.',copy:'Якісні фото не доводять наявність товару: їх легко скопіювати з сайту виробника або іншого магазину.',key:false,icon:'IMG'},
{id:'payment',type:'Листування з продавцем',title:'Повна передоплата на особисту картку',preview:'«Оплата тільки зараз»',visual:'ЧАТ ІЗ ПРОДАВЦЕМ\n\n«Резервуємо товар після 100% оплати.\nПереказуйте 2 750 грн на картку 5168 **** **** 2741.\nФОП/рахунку немає, бо це складська акція».',copy:'Вимога повної передоплати на особисту картку без зрозумілих реквізитів продавця та захисту покупця суттєво підвищує ризик.',key:true,icon:'₴'},
{id:'comment',type:'Коментар у соцмережі',title:'«Мені подобається цей бренд»',preview:'Особиста думка · без покупки',visual:'КОМЕНТАР\n\n«Цей бренд навушників загалом класний, користуюся іншим моделем уже два роки».',copy:'Враження про бренд не підтверджує надійність конкретного продавця або цього магазину.',key:false,icon:'♥'},
{id:'domain',type:'Дані сайту',title:'Домен зареєстровано 9 днів тому',preview:'Новий сайт · власник прихований',visual:'ДАНІ ДОМЕНУ\n\nДата реєстрації: 9 днів тому\nКонтакт власника: приховано\nАдреса в реєстрі: відсутня',copy:'Дуже новий домен не є автоматичним доказом шахрайства, але разом з іншими ознаками вимагає підвищеної обережності.',key:true,icon:'WWW'},
{id:'details',type:'Сторінка «Контакти»',title:'Немає назви продавця й реквізитів',preview:'Лише месенджер · без адреси',visual:'КОНТАКТИ\n\nTelegram: @sale_fast_ua\nТелефон: не вказано\nНазва продавця: не вказано\nКод/ЄДРПОУ: не вказано\nАдреса для повернення: не вказано',copy:'Відсутність ідентифікаційних і контактних даних ускладнює перевірку продавця та подальше пред’явлення вимог.',key:true,icon:'ID'},
{id:'delivery',type:'Скрін перевізника',title:'У місті працює доставка наступного дня',preview:'Загальна інформація',visual:'СЛУЖБА ДОСТАВКИ\n\nДоставка між відділеннями можлива наступного дня.',copy:'Швидкість роботи перевізника не підтверджує, що конкретний продавець справді передав товар на відправлення.',key:false,icon:'24h'},
{id:'reviews',type:'Відгуки про магазин',title:'Однакові тексти й дати публікацій',preview:'18 відгуків за 40 хвилин',visual:'ВІДГУКИ\n\n«Супер магазин, усе топ!» — 14:02\n«Супер магазин, усе топ!» — 14:07\n«Супер магазин, усе топ!» — 14:11\n...\n18 відгуків створено протягом 40 хвилин.',copy:'Неприродно однакові відгуки, опубліковані майже одночасно, можуть бути штучними і не дають надійного підтвердження репутації.',key:true,icon:'★'}
];

const risks=[
{id:'a',label:'Висновок А',text:'Знижка 45% автоматично означає шахрайство, тому інші ознаки перевіряти не потрібно.',correct:false},
{id:'b',label:'Висновок Б',text:'Поєднання нового домену, відсутніх реквізитів, підозрілих відгуків і вимоги 100% передоплати на особисту картку створює високий ризик. До оплати продавця треба було додатково перевірити або відмовитися від угоди.',correct:true},
{id:'c',label:'Висновок В',text:'Якщо на сайті є якісні фото й таймер акції, магазин можна вважати перевіреним.',correct:false},
{id:'d',label:'Висновок Г',text:'Ризику немає, бо сума менша за 3 000 грн і шахраї працюють лише з великими платежами.',correct:false}
];

const suspects=[
{id:'delivery',mark:'01',title:'Збій служби доставки',text:'У справі немає підтвердження, що товар взагалі був переданий перевізнику.',correct:false},
{id:'fake',mark:'02',title:'Фальшивий магазин для збору передоплат',text:'Сайт створював довіру за допомогою акції та відгуків, переводив покупця в месенджер і вимагав незахищену передоплату, після чого зникав.',correct:true},
{id:'brand',mark:'03',title:'Помилка виробника навушників',text:'Виробник товару не контролював оплату на особисту картку продавця і не пояснює зникнення сайту.',correct:false},
{id:'bank',mark:'04',title:'Банк випадково заблокував замовлення',text:'Переказ був виконаний; проблема полягає не в банківській операції, а у відсутності реального продавця та товару.',correct:false}
];

const plans=[
{id:'seller',mark:'01',title:'Перевірити реквізити й історію продавця',text:'Знайти назву суб’єкта, контакти, адресу, умови повернення та незалежні згадки про магазин.',correct:true},
{id:'timer',mark:'02',title:'Платити швидше, поки не закінчився таймер',text:'Тиск часу — причина уповільнитися й перевірити продавця, а не пришвидшувати переказ.',correct:false},
{id:'market',mark:'03',title:'Порівняти ціну з ринковою',text:'Велике відхилення від звичної ціни має бути приводом перевірити причину знижки та репутацію магазину.',correct:true},
{id:'protected',mark:'04',title:'Обрати оплату із захистом покупця',text:'За можливості використовувати післяплату, еквайринг або платформу, де є зрозумілий механізм спору та підтвердження замовлення.',correct:true},
{id:'trust',mark:'05',title:'Довіряти відгукам лише на самому сайті',text:'Відгуки на сторінці продавця можуть бути сфабриковані; потрібні незалежні джерела та перевірка деталей.',correct:false},
{id:'records',mark:'06',title:'Зберегти сторінку, листування й підтвердження оплати',text:'Фіксація умов, контактів і платежу допомагає при зверненні до банку, платформи або правоохоронців.',correct:true}
];

const state={viewed:new Set(),selected:new Set(),risk:null,suspect:null,plans:new Set(),evidenceScore:0,riskScore:0,verdictScore:0,planScore:0,currentEvidence:null};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];

function renderEvidence(){const cards=evidence.map((x,i)=>`<button class="evidence-card" data-evidence="${x.id}" type="button"><span class="evidence-top"><span>МАТЕРІАЛ ${String(i+1).padStart(2,'0')}</span><b class="evidence-state">Не оглянуто</b></span><span class="evidence-icon">${x.icon}</span><span class="evidence-type">${x.type}</span><strong>${x.title}</strong><small>${x.preview}</small><em>Відкрити документ →</em></button>`).join('');$('#evidence-board').innerHTML=`<header class="board-toolbar"><div><span>СЛІДИ ПРОДАВЦЯ · CB-30714</span><strong>Матеріали онлайн-покупки</strong></div><div><small>Оглянуто</small><b id="board-viewed">0 / 8</b></div></header><div class="board-canvas">${cards}</div><section class="selection-folder"><header><div><span>РОБОЧА ПАПКА</span><strong>Ключові сигнали ризику</strong></div><small>Рівно 5 матеріалів</small></header><ol id="selected-evidence"></ol></section>`}
function renderChoices(){$('#risk-options').innerHTML=risks.map(x=>`<button class="choice-option" data-risk="${x.id}" type="button"><span class="option-mark">${x.label.slice(-1)}</span><span><strong>${x.label}</strong><small>${x.text}</small></span></button>`).join('');$('#suspects').innerHTML=suspects.map(x=>`<button class="choice-option" data-suspect="${x.id}" type="button"><span class="option-mark">${x.mark}</span><span><strong>${x.title}</strong><small>${x.text}</small></span></button>`).join('');$('#plan-options').innerHTML=plans.map(x=>`<button class="choice-option" data-plan="${x.id}" type="button"><span class="option-mark">${x.mark}</span><span><strong>${x.title}</strong><small>${x.text}</small></span></button>`).join('')}
function updateDashboard(stage=1){$('#dash-stage').textContent=`${stage} / 4`;$('#dash-viewed').textContent=`${state.viewed.size} / 8`;$('#dash-selected').textContent=`${state.selected.size} / 5`;const earned=state.evidenceScore+state.riskScore+state.verdictScore+state.planScore;const available=[0,40,60,80,100][stage];$('#dash-score').textContent=`${Math.round(earned/available*100)||0}%`}
function openEvidence(id){const x=evidence.find(e=>e.id===id);state.currentEvidence=id;state.viewed.add(id);$('#modal-label').textContent=`Матеріал справи · ${x.type}`;$('#modal-title').textContent=x.title;$('#modal-visual').textContent=x.visual;$('#modal-copy').textContent=x.copy;updateEvidence();updateModalButton();$('#evidence-modal').hidden=false;document.body.classList.add('modal-open')}
function closeModal(){$('#evidence-modal').hidden=true;document.body.classList.remove('modal-open');state.currentEvidence=null}
function updateModalButton(){const yes=state.selected.has(state.currentEvidence);$('#modal-select').textContent=yes?'Вилучити з робочої папки':'Долучити до робочої папки';$('#modal-select').classList.toggle('is-remove',yes)}
function toggleEvidence(){const id=state.currentEvidence;if(state.selected.has(id))state.selected.delete(id);else if(state.selected.size<5)state.selected.add(id);updateModalButton();updateEvidence()}
function updateEvidence(){$$('.evidence-card').forEach(card=>{const id=card.dataset.evidence,viewed=state.viewed.has(id),selected=state.selected.has(id);card.classList.toggle('is-viewed',viewed);card.classList.toggle('is-selected',selected);card.querySelector('.evidence-state').textContent=selected?'Долучено':viewed?'Оглянуто':'Не оглянуто'});$('#board-viewed').textContent=`${state.viewed.size} / 8`;const chosen=[...state.selected].map(id=>evidence.find(x=>x.id===id));$('#selected-evidence').innerHTML=Array.from({length:5},(_,i)=>chosen[i]?`<li class="is-filled"><span>${i+1}</span><strong>${chosen[i].title}</strong><button type="button" data-remove="${chosen[i].id}" aria-label="Вилучити ${chosen[i].title}">×</button></li>`:`<li><span>${i+1}</span><em>Вільне місце для доказу</em></li>`).join('');const all=state.viewed.size===8,full=state.selected.size===5;$('#check-evidence').disabled=!(all&&full);$('#evidence-hint').textContent=!all?`Оглянуто ${state.viewed.size} із 8 матеріалів.`:!full?`Долучено ${state.selected.size} із 5 доказів.`:'Усі матеріали оглянуто. Можна зафіксувати докази.';updateDashboard(1)}
function showStage(id,number){$$('.stage').forEach(x=>x.classList.remove('is-active'));$(id).classList.add('is-active');updateDashboard(number);window.scrollTo({top:$(id).offsetTop-90,behavior:'smooth'})}
function chooseOne(selector,key,id,button){state[key]=id;$$(selector).forEach(x=>x.classList.remove('is-selected'));button.classList.add('is-selected')}
function checkEvidence(){const keys=evidence.filter(x=>x.key).map(x=>x.id);state.evidenceScore=keys.filter(x=>state.selected.has(x)).length*8;showStage('#stage-risk',2)}
function checkRisk(){state.riskScore=risks.find(x=>x.id===state.risk)?.correct?20:0;showStage('#stage-verdict',3)}
function checkVerdict(){state.verdictScore=suspects.find(x=>x.id===state.suspect)?.correct?20:0;showStage('#stage-plan',4)}
function togglePlan(id,button){if(state.plans.has(id)){state.plans.delete(id);button.classList.remove('is-selected')}else if(state.plans.size<4){state.plans.add(id);button.classList.add('is-selected')}$('#finish-button').disabled=state.plans.size!==4;$('#plan-hint').textContent=`Обрано ${state.plans.size} із 4 дій.`}
function finish(){state.planScore=plans.filter(x=>x.correct&&state.plans.has(x.id)).length*5;const score=state.evidenceScore+state.riskScore+state.verdictScore+state.planScore;$('#stage-plan').classList.remove('is-active');$('.case-dashboard').style.display='none';$('#result').classList.add('is-visible');$('#result-score').textContent=`${score} / 100`;const level=score>=90?['Схему продавця викрито','Ви правильно зібрали сигнали ризику, оцінили сукупність ознак і сформували безпечний алгоритм покупки.']:score>=70?['Основний ризик встановлено','Ключову схему ви розпізнали, але в доказах або протоколі залишилися неточності.']:['У справі залишилися прогалини','Поверніться до реквізитів продавця, способу оплати, віку домену та характеру відгуків: разом вони дають сильніший висновок, ніж одна низька ціна.'];$('#result-title').textContent=level[0];$('#result-lead').textContent=level[1];const missed=evidence.filter(x=>x.key&&!state.selected.has(x.id)).map(x=>x.title),noise=evidence.filter(x=>!x.key&&state.selected.has(x.id)).map(x=>x.title),wrong=plans.filter(x=>!x.correct&&state.plans.has(x.id)).map(x=>x.title);$('#report-content').innerHTML=`<p><strong>Докази:</strong> ${state.evidenceScore===40?'усі п’ять ключових сигналів визначено правильно.':`пропущено: ${missed.join(', ')||'немає'}; зайві: ${noise.join(', ')||'немає'}.`}</p><p><strong>Оцінка ризику:</strong> ${state.riskScore?'правильно враховано сукупність ознак, а не лише розмір знижки.':'висновок недооцінює важливість перевірки продавця до передоплати.'}</p><p><strong>Механізм:</strong> ${state.verdictScore?'встановлено схему фальшивого магазину для збору передоплат.':'обрана версія не пояснює одночасно передоплату, зникнення сайту та відсутність товару.'}</p><p><strong>Протокол:</strong> ${state.planScore===20?'усі чотири безпечні дії обрано правильно.':`ризикові рішення: ${wrong.join(', ')||'частину необхідних дій не обрано'}.`}</p>`;window.scrollTo({top:$('#result').offsetTop-30,behavior:'smooth'})}
function reset(){state.viewed.clear();state.selected.clear();state.plans.clear();state.risk=null;state.suspect=null;state.evidenceScore=state.riskScore=state.verdictScore=state.planScore=0;$('.case-dashboard').style.display='grid';$('#result').classList.remove('is-visible');$$('.is-selected,.is-viewed').forEach(x=>x.classList.remove('is-selected','is-viewed'));$('#check-risk').disabled=true;$('#check-verdict').disabled=true;$('#finish-button').disabled=true;$('#plan-hint').textContent='Оберіть 4 дії.';showStage('#stage-evidence',1);updateEvidence()}

renderEvidence();renderChoices();
$('#start-button').addEventListener('click',()=>{$('#investigation').classList.add('is-visible');$('#briefing').style.display='none';window.scrollTo({top:$('#investigation').offsetTop-20,behavior:'smooth'})});
$('#evidence-board').addEventListener('click',e=>{const remove=e.target.closest('[data-remove]');if(remove){state.selected.delete(remove.dataset.remove);updateEvidence();return}const card=e.target.closest('[data-evidence]');if(card)openEvidence(card.dataset.evidence)});
$('#modal-select').addEventListener('click',toggleEvidence);$$('[data-close-modal]').forEach(x=>x.addEventListener('click',closeModal));document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!$('#evidence-modal').hidden)closeModal()});
$('#check-evidence').addEventListener('click',checkEvidence);
$('#risk-options').addEventListener('click',e=>{const b=e.target.closest('[data-risk]');if(!b)return;chooseOne('.choice-option[data-risk]','risk',b.dataset.risk,b);$('#check-risk').disabled=false});$('#check-risk').addEventListener('click',checkRisk);
$('#suspects').addEventListener('click',e=>{const b=e.target.closest('[data-suspect]');if(!b)return;chooseOne('.choice-option[data-suspect]','suspect',b.dataset.suspect,b);$('#check-verdict').disabled=false});$('#check-verdict').addEventListener('click',checkVerdict);
$('#plan-options').addEventListener('click',e=>{const b=e.target.closest('[data-plan]');if(b)togglePlan(b.dataset.plan,b)});$('#finish-button').addEventListener('click',finish);$('#restart-button').addEventListener('click',reset);