const evidence=[
{id:'offer',type:'Офер',title:'Зарплата 20 000 грн',preview:'Сума до утримань',visual:'ПРОПОЗИЦІЯ ПРО РОБОТУ\n\nПосада: помічник менеджера\nЗарплата: 20 000 грн на місяць\n\nУ навчальному прикладі це сума до утримань.',copy:'Офер фіксує базову нараховану зарплату, від якої виконується розрахунок.',key:true,icon:'20'},
{id:'chat',type:'Повідомлення знайомого',title:'«Роботодавець забрав ще 22%»',preview:'Припущення без розрахунку',visual:'ЧАТ\n\n«Тобі нарахували 20 000, потім забрали 23%, а потім ще 22%. Так завжди».',copy:'Твердження змішує утримання працівника з окремим внеском роботодавця. Його треба перевірити за документами.',key:false,icon:'?'},
{id:'payslip',type:'Розрахунковий лист',title:'Утримано 3 600 грн і 1 000 грн',preview:'18% + 5%',visual:'РОЗРАХУНКОВИЙ ЛИСТ\n\nНараховано ........ 20 000 грн\nУтримання 18% ...... 3 600 грн\nУтримання 5% ....... 1 000 грн\nДо виплати ......... 15 400 грн',copy:'Це прямий документ, який пояснює різницю між нарахованою сумою та виплатою.',key:true,icon:'='},
{id:'coffee',type:'Банківська операція',title:'Кава за 95 грн',preview:'Особиста витрата після зарплати',visual:'КАРТКА\n\nКав’ярня\nСума: -95 грн\nЧас: 09:14',copy:'Це вже особиста витрата після отримання зарплати. Вона не пояснює, чому роботодавець перерахував 15 400 грн.',key:false,icon:'95'},
{id:'payment',type:'Банківське зарахування',title:'На картку надійшло 15 400 грн',preview:'Зарплатний платіж',visual:'БАНК\n\nЗарахування зарплати\n+15 400 грн\nПризначення: заробітна плата',copy:'Банківське зарахування підтверджує фактичну суму, яку працівниця отримала після утримань.',key:true,icon:'₴'},
{id:'employer',type:'Довідка роботодавця',title:'Додатковий внесок 22% сплачує роботодавець',preview:'4 400 грн понад нараховану зарплату',visual:'ВИТРАТИ РОБОТОДАВЦЯ\n\nНарахована зарплата: 20 000 грн\nОкремий внесок роботодавця 22%: 4 400 грн\nЗагальні витрати: 24 400 грн\n\nЦей внесок не віднімається з 20 000 грн працівника.',copy:'Документ відділяє зарплатні утримання від окремої витрати роботодавця.',key:true,icon:'22%'},
{id:'bonus',type:'Стара вакансія',title:'Бонус до 5 000 грн після випробувального строку',preview:'Умова ще не настала',visual:'АРХІВ ВАКАНСІЇ\n\nМожливий бонус: до 5 000 грн\nПісля 3 місяців роботи\nЗа виконання KPI',copy:'Майбутній умовний бонус не входить до зарплати за перший місяць і не пояснює поточну виплату.',key:false,icon:'+5'},
{id:'rates',type:'Умова навчального прикладу',title:'Ставки для розрахунку: 18% і 5%',preview:'Застосовуються до 20 000 грн',visual:'УМОВА СПРАВИ\n\nДля цього навчального розрахунку:\n• утримання А — 18%\n• утримання Б — 5%\n• база — 20 000 грн\n\nАктуальні реальні ставки перевіряють окремо.',copy:'Цей матеріал задає ставки, які треба застосувати в межах задачі.',key:true,icon:'%' }
];
const calculations=[
{id:'a',label:'Розрахунок А',text:'20 000 − 18% − 5% = 15 400 грн: 3 600 грн + 1 000 грн утримань.',correct:true},
{id:'b',label:'Розрахунок Б',text:'20 000 − 18% − 5% − 22% = 11 000 грн, бо всі відсотки віднімаються із зарплати працівника.',correct:false},
{id:'c',label:'Розрахунок В',text:'20 000 × 0,18 × 0,05 = 180 грн утримань, тому до виплати 19 820 грн.',correct:false},
{id:'d',label:'Розрахунок Г',text:'15 400 грн — це випадкова сума, бо податки не можна перевірити арифметично.',correct:false}
];
const suspects=[
{id:'same',mark:'01',title:'Усі 45% треба відняти із зарплати',text:'Це змішує різні платежі та подвійно зменшує зарплату працівника.',correct:false},
{id:'employer',mark:'02',title:'22% — окрема витрата роботодавця',text:'За умовою справи роботодавець нараховує 4 400 грн понад зарплату; ця сума не віднімається ще раз із 20 000 грн Ірини.',correct:true},
{id:'bank',mark:'03',title:'Банк утримав різницю між 20 000 і 15 400',text:'Банк лише зарахував уже розраховану суму; матеріали не показують банківської комісії 4 600 грн.',correct:false},
{id:'bonus',mark:'04',title:'Різниця виникла через ненарахований бонус',text:'Бонус ще не був зароблений і не входив у нараховані 20 000 грн.',correct:false}
];
const plans=[
{id:'gross',mark:'01',title:'Уточнювати, зарплата вказана до чи після утримань',text:'Слова gross/net або «нараховано/до виплати» принципово змінюють очікувану суму на картці.',correct:true},
{id:'subtract',mark:'02',title:'Віднімати з зарплати всі відсотки, які бачите в документах',text:'Спочатку треба встановити, хто саме сплачує кожен платіж. Не всі внески є утриманнями працівника.',correct:false},
{id:'payslip',mark:'03',title:'Звіряти розрахунковий лист із банківським зарахуванням',text:'Нарахування, утримання та сума до виплати мають складатися в один арифметичний ланцюг.',correct:true},
{id:'roles',mark:'04',title:'Розділяти платежі працівника і роботодавця',text:'Це запобігає подвійним відніманням і хибному уявленню про зарплату.',correct:true},
{id:'rumor',mark:'05',title:'Орієнтуватися на поради знайомих без документів',text:'Податкові розрахунки треба перевіряти за умовами договору, розрахунковим листом і офіційними правилами.',correct:false},
{id:'current',mark:'06',title:'Для реальної зарплати перевіряти чинні ставки',text:'Навчальний приклад має задані числа, а реальні правила можуть змінюватися.',correct:true}
];
const state={viewed:new Set(),selected:new Set(),calculation:null,suspect:null,plans:new Set(),evidenceScore:0,calculationScore:0,verdictScore:0,planScore:0,currentEvidence:null};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
function renderEvidence(){const cards=evidence.map((x,i)=>`<button class="evidence-card" data-evidence="${x.id}" type="button"><span class="evidence-top"><span>МАТЕРІАЛ ${String(i+1).padStart(2,'0')}</span><b class="evidence-state">Не оглянуто</b></span><span class="evidence-icon">${x.icon}</span><span class="evidence-type">${x.type}</span><strong>${x.title}</strong><small>${x.preview}</small><em>Відкрити документ →</em></button>`).join('');$('#evidence-board').innerHTML=`<header class="board-toolbar"><div><span>ЗАРПЛАТНІ СЛІДИ · CB-20023</span><strong>Матеріали розрахунку</strong></div><div><small>Оглянуто</small><b id="board-viewed">0 / 8</b></div></header><div class="board-canvas">${cards}</div><section class="selection-folder"><header><div><span>РОБОЧА ПАПКА</span><strong>Ключові докази розрахунку</strong></div><small>Рівно 5 матеріалів</small></header><ol id="selected-evidence"></ol></section>`}
function renderChoices(){$('#calculation-options').innerHTML=calculations.map(x=>`<button class="choice-option" data-calculation="${x.id}" type="button"><span class="option-mark">${x.label.slice(-1)}</span><span><strong>${x.label}</strong><small>${x.text}</small></span></button>`).join('');$('#suspects').innerHTML=suspects.map(x=>`<button class="choice-option" data-suspect="${x.id}" type="button"><span class="option-mark">${x.mark}</span><span><strong>${x.title}</strong><small>${x.text}</small></span></button>`).join('');$('#plan-options').innerHTML=plans.map(x=>`<button class="choice-option" data-plan="${x.id}" type="button"><span class="option-mark">${x.mark}</span><span><strong>${x.title}</strong><small>${x.text}</small></span></button>`).join('')}
function updateDashboard(stage=1){$('#dash-stage').textContent=`${stage} / 4`;$('#dash-viewed').textContent=`${state.viewed.size} / 8`;$('#dash-selected').textContent=`${state.selected.size} / 5`;const earned=state.evidenceScore+state.calculationScore+state.verdictScore+state.planScore;const available=[0,40,60,80,100][stage];$('#dash-score').textContent=`${Math.round(earned/available*100)||0}%`}
function openEvidence(id){const x=evidence.find(e=>e.id===id);state.currentEvidence=id;state.viewed.add(id);$('#modal-label').textContent=`Матеріал справи · ${x.type}`;$('#modal-title').textContent=x.title;$('#modal-visual').textContent=x.visual;$('#modal-copy').textContent=x.copy;updateEvidence();updateModalButton();$('#evidence-modal').hidden=false;document.body.classList.add('modal-open')}
function closeModal(){$('#evidence-modal').hidden=true;document.body.classList.remove('modal-open');state.currentEvidence=null}
function updateModalButton(){const yes=state.selected.has(state.currentEvidence);$('#modal-select').textContent=yes?'Вилучити з робочої папки':'Долучити до робочої папки';$('#modal-select').classList.toggle('is-remove',yes)}
function toggleEvidence(){const id=state.currentEvidence;if(state.selected.has(id))state.selected.delete(id);else if(state.selected.size<5)state.selected.add(id);updateModalButton();updateEvidence()}
function updateEvidence(){$$('.evidence-card').forEach(card=>{const id=card.dataset.evidence,viewed=state.viewed.has(id),selected=state.selected.has(id);card.classList.toggle('is-viewed',viewed);card.classList.toggle('is-selected',selected);card.querySelector('.evidence-state').textContent=selected?'Долучено':viewed?'Оглянуто':'Не оглянуто'});$('#board-viewed').textContent=`${state.viewed.size} / 8`;const chosen=[...state.selected].map(id=>evidence.find(x=>x.id===id));$('#selected-evidence').innerHTML=Array.from({length:5},(_,i)=>chosen[i]?`<li class="is-filled"><span>${i+1}</span><strong>${chosen[i].title}</strong><button type="button" data-remove="${chosen[i].id}" aria-label="Вилучити ${chosen[i].title}">×</button></li>`:`<li><span>${i+1}</span><em>Вільне місце для доказу</em></li>`).join('');const all=state.viewed.size===8,full=state.selected.size===5;$('#check-evidence').disabled=!(all&&full);$('#evidence-hint').textContent=!all?`Оглянуто ${state.viewed.size} із 8 матеріалів.`:!full?`Долучено ${state.selected.size} із 5 доказів.`:'Усі матеріали оглянуто. Можна зафіксувати докази.';updateDashboard(1)}
function showStage(id,number){$$('.stage').forEach(x=>x.classList.remove('is-active'));$(id).classList.add('is-active');updateDashboard(number);window.scrollTo({top:$(id).offsetTop-90,behavior:'smooth'})}
function chooseOne(selector,key,id,button){state[key]=id;$$(selector).forEach(x=>x.classList.remove('is-selected'));button.classList.add('is-selected')}
function checkEvidence(){const keys=evidence.filter(x=>x.key).map(x=>x.id);state.evidenceScore=keys.filter(x=>state.selected.has(x)).length*8;showStage('#stage-calculation',2)}
function checkCalculation(){state.calculationScore=calculations.find(x=>x.id===state.calculation)?.correct?20:0;showStage('#stage-verdict',3)}
function checkVerdict(){state.verdictScore=suspects.find(x=>x.id===state.suspect)?.correct?20:0;showStage('#stage-plan',4)}
function togglePlan(id,button){if(state.plans.has(id)){state.plans.delete(id);button.classList.remove('is-selected')}else if(state.plans.size<4){state.plans.add(id);button.classList.add('is-selected')}$('#finish-button').disabled=state.plans.size!==4;$('#plan-hint').textContent=`Обрано ${state.plans.size} із 4 дій.`}
function finish(){state.planScore=plans.filter(x=>x.correct&&state.plans.has(x.id)).length*5;const score=state.evidenceScore+state.calculationScore+state.verdictScore+state.planScore;$('#stage-plan').classList.remove('is-active');$('.case-dashboard').style.display='none';$('#result').classList.add('is-visible');$('#result-score').textContent=`${score} / 100`;const level=score>=90?['Зарплатний розрахунок відновлено','Ви правильно відділили нараховану зарплату, утримання працівника, виплату на картку та окремі витрати роботодавця.']:score>=70?['Основний розрахунок встановлено','Логіка зарплати зрозуміла, але в частині доказів або класифікації платежів залишилися неточності.']:['У розрахунку залишилися прогалини','Поверніться до офера, ставок, розрахункового листа, банківської виплати та довідки про внесок роботодавця.'];$('#result-title').textContent=level[0];$('#result-lead').textContent=level[1];const missed=evidence.filter(x=>x.key&&!state.selected.has(x.id)).map(x=>x.title),noise=evidence.filter(x=>!x.key&&state.selected.has(x.id)).map(x=>x.title),wrong=plans.filter(x=>!x.correct&&state.plans.has(x.id)).map(x=>x.title);$('#report-content').innerHTML=`<p><strong>Докази:</strong> ${state.evidenceScore===40?'усі п’ять ключових матеріалів визначено правильно.':`пропущено: ${missed.join(', ')||'немає'}; зайві: ${noise.join(', ')||'немає'}.`}</p><p><strong>Розрахунок:</strong> ${state.calculationScore?'20 000 − 3 600 − 1 000 = 15 400 грн.':'обраний варіант неправильно застосовує ставки або змішує внесок роботодавця з утриманнями.'}</p><p><strong>Класифікація:</strong> ${state.verdictScore?'встановлено, що 22% у цій справі є окремою витратою роботодавця.':'висновок не розділяє платежі працівника та роботодавця.'}</p><p><strong>Алгоритм:</strong> ${state.planScore===20?'усі чотири дії перевірки обрано правильно.':`ризикові рішення: ${wrong.join(', ')||'частину необхідних дій не обрано'}.`}</p>`;window.scrollTo({top:$('#result').offsetTop-30,behavior:'smooth'})}
function reset(){state.viewed.clear();state.selected.clear();state.plans.clear();state.calculation=null;state.suspect=null;state.evidenceScore=state.calculationScore=state.verdictScore=state.planScore=0;$('.case-dashboard').style.display='grid';$('#result').classList.remove('is-visible');$$('.is-selected,.is-viewed').forEach(x=>x.classList.remove('is-selected','is-viewed'));$('#check-calculation').disabled=true;$('#check-verdict').disabled=true;$('#finish-button').disabled=true;$('#plan-hint').textContent='Оберіть 4 дії.';showStage('#stage-evidence',1);updateEvidence()}
renderEvidence();renderChoices();
$('#start-button').addEventListener('click',()=>{$('#investigation').classList.add('is-visible');$('#briefing').style.display='none';window.scrollTo({top:$('#investigation').offsetTop-20,behavior:'smooth'})});
$('#evidence-board').addEventListener('click',e=>{const remove=e.target.closest('[data-remove]');if(remove){state.selected.delete(remove.dataset.remove);updateEvidence();return}const card=e.target.closest('[data-evidence]');if(card)openEvidence(card.dataset.evidence)});
$('#modal-select').addEventListener('click',toggleEvidence);$$('[data-close-modal]').forEach(x=>x.addEventListener('click',closeModal));document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!$('#evidence-modal').hidden)closeModal()});
$('#check-evidence').addEventListener('click',checkEvidence);
$('#calculation-options').addEventListener('click',e=>{const b=e.target.closest('[data-calculation]');if(!b)return;chooseOne('.choice-option[data-calculation]','calculation',b.dataset.calculation,b);$('#check-calculation').disabled=false});$('#check-calculation').addEventListener('click',checkCalculation);
$('#suspects').addEventListener('click',e=>{const b=e.target.closest('[data-suspect]');if(!b)return;chooseOne('.choice-option[data-suspect]','suspect',b.dataset.suspect,b);$('#check-verdict').disabled=false});$('#check-verdict').addEventListener('click',checkVerdict);
$('#plan-options').addEventListener('click',e=>{const b=e.target.closest('[data-plan]');if(b)togglePlan(b.dataset.plan,b)});$('#finish-button').addEventListener('click',finish);$('#restart-button').addEventListener('click',reset);