const evidence=[
{id:'sms',type:'SMS-повідомлення',title:'«Картку заблоковано»',preview:'Терміновий текст · посилання bank-secure.help',visual:'SMS · 18:42\n\n«Вашу картку тимчасово заблоковано через підозрілу операцію. Для підтвердження особи перейдіть: bank-secure.help/verify»',copy:'Повідомлення створює терміновість і веде не на офіційний домен банку. Це типовий початок фішингової атаки.',key:true,icon:'SMS'},
{id:'site',type:'Фішингова сторінка',title:'Копія сайту банку',preview:'Логотип схожий · адреса інша',visual:'АДРЕСНИЙ РЯДОК\nhttps://bank-secure.help/verify\n\nФорма просить:\n• номер картки\n• строк дії\n• CVV\n• код із SMS',copy:'Зовнішній вигляд можна скопіювати, а домен — ні. Сторінка збирає дані, яких банк не просить для скасування блокування.',key:true,icon:'WWW'},
{id:'otp',type:'Повідомлення банку',title:'Одноразовий код 731204',preview:'«Не повідомляйте код нікому»',visual:'БАНК · 18:46\n\nКод підтвердження онлайн-платежу: 731204.\nСума: 4 800 грн.\n\nНІКОМУ НЕ ПОВІДОМЛЯЙТЕ ЦЕЙ КОД. Працівники банку його не запитують.',copy:'Код підтверджував конкретний платіж на 4 800 грн. Передача коду дала змогу завершити операцію.',key:true,icon:'OTP'},
{id:'history',type:'Історія операцій',title:'Списання 4 800 грн',preview:'18:49 · online merchant',visual:'ІСТОРІЯ ОПЕРАЦІЙ\n\n18:49  ONLINE MERCHANT\nСписання ........ 4 800 грн\nСтатус ........... виконано\nКанал ............ online / 3-D Secure',copy:'Запис підтверджує час, суму й тип операції. Він пов’язує одноразовий код із фактичним списанням.',key:true,icon:'₴'},
{id:'official',type:'Офіційна пам’ятка банку',title:'Що банк ніколи не запитує',preview:'PIN · CVV · одноразові коди',visual:'ПАМ’ЯТКА БЕЗПЕКИ\n\nБанк ніколи не просить:\n• PIN-код\n• CVV/CVC\n• пароль до застосунку\n• одноразовий код із SMS\n\nПеревіряйте звернення через офіційний застосунок або номер на картці.',copy:'Пам’ятка дає правило, за яким можна відрізнити легітимну перевірку від соціальної інженерії.',key:true,icon:'!'},
{id:'friend',type:'Чат із другом',title:'«Може, це технічний збій»',preview:'Припущення без доказів',visual:'ЧАТ · 18:52\n\n«Може, у банку просто збій і гроші повернуться самі. Я б нічого не блокував до завтра».',copy:'Це припущення. При несанкціонованій операції зволікання збільшує ризик повторних списань.',key:false,icon:'?'},
{id:'receipt',type:'Чек із магазину',title:'Покупка кави на 96 грн',preview:'17:10 · фізичний термінал',visual:'ЧЕК\n\nКава + сендвіч\nСума: 96 грн\nЧас: 17:10\nОплата карткою через термінал',copy:'Звичайна фізична покупка не пояснює онлайн-операцію о 18:49 і не містить доказів передачі реквізитів шахраям.',key:false,icon:'96'},
{id:'wifi',type:'Список Wi-Fi',title:'Підключення до кафе',preview:'Гостьова мережа · без зв’язку з оплатою',visual:'WI-FI\n\nCafe_Free_WiFi\nПідключено о 17:05\nВідключено о 17:32',copy:'Сам факт використання публічного Wi-Fi не доводить причину списання. У справі є пряміші докази фішингу та підтвердження платежу.',key:false,icon:'WiFi'}
];
const timelines=[
{id:'a',label:'Версія А',text:'Банк сам заблокував картку, після чого автоматично списав 4 800 грн для перевірки особи.',correct:false},
{id:'b',label:'Версія Б',text:'SMS привело на підроблений сайт → Олена ввела реквізити картки → шахраї ініціювали онлайн-платіж → Олена ввела одноразовий код → платіж підтвердився.',correct:true},
{id:'c',label:'Версія В',text:'Дані картки викрали через касовий термінал у кафе, а SMS банку з’явилося вже після списання.',correct:false},
{id:'d',label:'Версія Г',text:'Публічний Wi-Fi автоматично передав банку CVV і код, тому сторінка з SMS не мала значення.',correct:false}
];
const suspects=[
{id:'click',mark:'01',title:'Сам перехід за посиланням',text:'Перехід був небезпечним, але без введених реквізитів і коду шахраям ще бракувало даних для підтвердження платежу.',correct:false},
{id:'card',mark:'02',title:'Введення номера картки та CVV',text:'Це серйозна компрометація реквізитів, але в цій справі онлайн-платіж додатково вимагав одноразового коду.',correct:false},
{id:'otp',mark:'03',title:'Введення одноразового коду',text:'Код із SMS підтверджував конкретний платіж на 4 800 грн. Його введення на фішинговій сторінці завершило атаку.',correct:true},
{id:'wifi',mark:'04',title:'Підключення до Wi-Fi у кафе',text:'У матеріалах немає доказів, що мережа була джерелом реквізитів або одноразового коду.',correct:false}
];
const plans=[
{id:'app',mark:'01',title:'Перевірити повідомлення через офіційний застосунок',text:'Не використовувати посилання з SMS, а самостійно відкрити банківський застосунок або офіційний сайт.',correct:true},
{id:'callback',mark:'02',title:'Подзвонити за номером із самого SMS',text:'Шахраї можуть підставити власний номер. Контакт треба брати з картки або офіційного сайту.',correct:false},
{id:'codes',mark:'03',title:'Нікому не передавати PIN, CVV та одноразові коди',text:'Такі дані не повідомляють «службі безпеки» й не вводять на сторінці з підозрілого посилання.',correct:true},
{id:'block',mark:'04',title:'Негайно заблокувати картку при невідомому списанні',text:'Швидке блокування зменшує ризик наступних операцій і дає змогу почати процедуру оскарження.',correct:true},
{id:'wait',mark:'05',title:'Почекати до завтра',text:'Зволікання після несанкціонованого списання створює ризик повторних операцій.',correct:false},
{id:'report',mark:'06',title:'Повідомити банк і зафіксувати обставини',text:'Зберегти SMS, адресу сайту й час подій та звернутися до банку щодо оскарження операції.',correct:true}
];
const state={viewed:new Set(),selected:new Set(),timeline:null,suspect:null,plans:new Set(),evidenceScore:0,timelineScore:0,verdictScore:0,planScore:0,currentEvidence:null};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
function renderEvidence(){const cards=evidence.map((x,i)=>`<button class="evidence-card" data-evidence="${x.id}" type="button"><span class="evidence-top"><span>МАТЕРІАЛ ${String(i+1).padStart(2,'0')}</span><b class="evidence-state">Не оглянуто</b></span><span class="evidence-icon">${x.icon}</span><span class="evidence-type">${x.type}</span><strong>${x.title}</strong><small>${x.preview}</small><em>Відкрити документ →</em></button>`).join('');$('#evidence-board').innerHTML=`<header class="board-toolbar"><div><span>ЦИФРОВІ СЛІДИ · CB-15007</span><strong>Матеріали атаки</strong></div><div><small>Оглянуто</small><b id="board-viewed">0 / 8</b></div></header><div class="board-canvas">${cards}</div><section class="selection-folder"><header><div><span>РОБОЧА ПАПКА</span><strong>Ключові докази атаки</strong></div><small>Рівно 5 матеріалів</small></header><ol id="selected-evidence"></ol></section>`}
function renderChoices(){$('#timeline-options').innerHTML=timelines.map(x=>`<button class="choice-option" data-timeline="${x.id}" type="button"><span class="option-mark">${x.label.slice(-1)}</span><span><strong>${x.label}</strong><small>${x.text}</small></span></button>`).join('');$('#suspects').innerHTML=suspects.map(x=>`<button class="choice-option" data-suspect="${x.id}" type="button"><span class="option-mark">${x.mark}</span><span><strong>${x.title}</strong><small>${x.text}</small></span></button>`).join('');$('#plan-options').innerHTML=plans.map(x=>`<button class="choice-option" data-plan="${x.id}" type="button"><span class="option-mark">${x.mark}</span><span><strong>${x.title}</strong><small>${x.text}</small></span></button>`).join('')}
function updateDashboard(stage=1){$('#dash-stage').textContent=`${stage} / 4`;$('#dash-viewed').textContent=`${state.viewed.size} / 8`;$('#dash-selected').textContent=`${state.selected.size} / 5`;const earned=state.evidenceScore+state.timelineScore+state.verdictScore+state.planScore;const available=[0,40,60,80,100][stage];$('#dash-score').textContent=`${Math.round(earned/available*100)||0}%`}
function openEvidence(id){const x=evidence.find(e=>e.id===id);state.currentEvidence=id;state.viewed.add(id);$('#modal-label').textContent=`Матеріал справи · ${x.type}`;$('#modal-title').textContent=x.title;$('#modal-visual').textContent=x.visual;$('#modal-copy').textContent=x.copy;updateEvidence();updateModalButton();$('#evidence-modal').hidden=false;document.body.classList.add('modal-open')}
function closeModal(){$('#evidence-modal').hidden=true;document.body.classList.remove('modal-open');state.currentEvidence=null}
function updateModalButton(){const yes=state.selected.has(state.currentEvidence);$('#modal-select').textContent=yes?'Вилучити з робочої папки':'Долучити до робочої папки';$('#modal-select').classList.toggle('is-remove',yes)}
function toggleEvidence(){const id=state.currentEvidence;if(state.selected.has(id))state.selected.delete(id);else if(state.selected.size<5)state.selected.add(id);updateModalButton();updateEvidence()}
function updateEvidence(){$$('.evidence-card').forEach(card=>{const id=card.dataset.evidence,viewed=state.viewed.has(id),selected=state.selected.has(id);card.classList.toggle('is-viewed',viewed);card.classList.toggle('is-selected',selected);card.querySelector('.evidence-state').textContent=selected?'Долучено':viewed?'Оглянуто':'Не оглянуто'});$('#board-viewed').textContent=`${state.viewed.size} / 8`;const chosen=[...state.selected].map(id=>evidence.find(x=>x.id===id));$('#selected-evidence').innerHTML=Array.from({length:5},(_,i)=>chosen[i]?`<li class="is-filled"><span>${i+1}</span><strong>${chosen[i].title}</strong><button type="button" data-remove="${chosen[i].id}" aria-label="Вилучити ${chosen[i].title}">×</button></li>`:`<li><span>${i+1}</span><em>Вільне місце для доказу</em></li>`).join('');const all=state.viewed.size===8,full=state.selected.size===5;$('#check-evidence').disabled=!(all&&full);$('#evidence-hint').textContent=!all?`Оглянуто ${state.viewed.size} із 8 матеріалів.`:!full?`Долучено ${state.selected.size} із 5 доказів.`:'Усі матеріали оглянуто. Можна зафіксувати докази.';updateDashboard(1)}
function showStage(id,number){$$('.stage').forEach(x=>x.classList.remove('is-active'));$(id).classList.add('is-active');updateDashboard(number);window.scrollTo({top:$(id).offsetTop-90,behavior:'smooth'})}
function chooseOne(selector,key,id,button){state[key]=id;$$(selector).forEach(x=>x.classList.remove('is-selected'));button.classList.add('is-selected')}
function checkEvidence(){const keys=evidence.filter(x=>x.key).map(x=>x.id);state.evidenceScore=keys.filter(x=>state.selected.has(x)).length*8;showStage('#stage-timeline',2)}
function checkTimeline(){state.timelineScore=timelines.find(x=>x.id===state.timeline)?.correct?20:0;showStage('#stage-verdict',3)}
function checkVerdict(){state.verdictScore=suspects.find(x=>x.id===state.suspect)?.correct?20:0;showStage('#stage-plan',4)}
function togglePlan(id,button){if(state.plans.has(id)){state.plans.delete(id);button.classList.remove('is-selected')}else if(state.plans.size<4){state.plans.add(id);button.classList.add('is-selected')}$('#finish-button').disabled=state.plans.size!==4;$('#plan-hint').textContent=`Обрано ${state.plans.size} із 4 дій.`}
function finish(){state.planScore=plans.filter(x=>x.correct&&state.plans.has(x.id)).length*5;const score=state.evidenceScore+state.timelineScore+state.verdictScore+state.planScore;$('#stage-plan').classList.remove('is-active');$('.case-dashboard').style.display='none';$('#result').classList.add('is-visible');$('#result-score').textContent=`${score} / 100`;const level=score>=90?['Цифровий слід відновлено','Ви правильно відокремили фішингові ознаки від шуму, відновили атаку й визначили роль одноразового коду.']:score>=70?['Механізм атаки переважно встановлено','Основний ланцюг зрозумілий, але в частині доказів або протоколу залишилися неточності.']:['У справі залишилися прогалини','Поверніться до SMS, адреси сайту, повідомлення з кодом та історії операцій: разом вони показують повний ланцюг атаки.'];$('#result-title').textContent=level[0];$('#result-lead').textContent=level[1];const missed=evidence.filter(x=>x.key&&!state.selected.has(x.id)).map(x=>x.title),noise=evidence.filter(x=>!x.key&&state.selected.has(x.id)).map(x=>x.title),wrong=plans.filter(x=>!x.correct&&state.plans.has(x.id)).map(x=>x.title);$('#report-content').innerHTML=`<p><strong>Докази:</strong> ${state.evidenceScore===40?'усі п’ять ключових матеріалів визначено правильно.':`пропущено: ${missed.join(', ')||'немає'}; зайві: ${noise.join(', ')||'немає'}.`}</p><p><strong>Хронологія:</strong> ${state.timelineScore?'правильно відновлено шлях від SMS до підтвердженого онлайн-платежу.':'обрана версія не узгоджується з часом і змістом повідомлень.'}</p><p><strong>Критична точка:</strong> ${state.verdictScore?'встановлено, що одноразовий код підтверджував конкретний платіж на 4 800 грн.':'висновок не враховує роль одноразового коду в підтвердженні операції.'}</p><p><strong>Протокол:</strong> ${state.planScore===20?'усі чотири захисні дії обрано правильно.':`ризикові рішення: ${wrong.join(', ')||'частину необхідних дій не обрано'}.`}</p>`;window.scrollTo({top:$('#result').offsetTop-30,behavior:'smooth'})}
function reset(){state.viewed.clear();state.selected.clear();state.plans.clear();state.timeline=null;state.suspect=null;state.evidenceScore=state.timelineScore=state.verdictScore=state.planScore=0;$('.case-dashboard').style.display='grid';$('#result').classList.remove('is-visible');$$('.is-selected,.is-viewed').forEach(x=>x.classList.remove('is-selected','is-viewed'));$('#check-timeline').disabled=true;$('#check-verdict').disabled=true;$('#finish-button').disabled=true;$('#plan-hint').textContent='Оберіть 4 дії.';showStage('#stage-evidence',1);updateEvidence()}
renderEvidence();renderChoices();
$('#start-button').addEventListener('click',()=>{$('#investigation').classList.add('is-visible');$('#briefing').style.display='none';window.scrollTo({top:$('#investigation').offsetTop-20,behavior:'smooth'})});
$('#evidence-board').addEventListener('click',e=>{const remove=e.target.closest('[data-remove]');if(remove){state.selected.delete(remove.dataset.remove);updateEvidence();return}const card=e.target.closest('[data-evidence]');if(card)openEvidence(card.dataset.evidence)});
$('#modal-select').addEventListener('click',toggleEvidence);$$('[data-close-modal]').forEach(x=>x.addEventListener('click',closeModal));document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!$('#evidence-modal').hidden)closeModal()});
$('#check-evidence').addEventListener('click',checkEvidence);
$('#timeline-options').addEventListener('click',e=>{const b=e.target.closest('[data-timeline]');if(!b)return;chooseOne('.choice-option[data-timeline]','timeline',b.dataset.timeline,b);$('#check-timeline').disabled=false});$('#check-timeline').addEventListener('click',checkTimeline);
$('#suspects').addEventListener('click',e=>{const b=e.target.closest('[data-suspect]');if(!b)return;chooseOne('.choice-option[data-suspect]','suspect',b.dataset.suspect,b);$('#check-verdict').disabled=false});$('#check-verdict').addEventListener('click',checkVerdict);
$('#plan-options').addEventListener('click',e=>{const b=e.target.closest('[data-plan]');if(b)togglePlan(b.dataset.plan,b)});$('#finish-button').addEventListener('click',finish);$('#restart-button').addEventListener('click',reset);