const initialState={money:7000,verification:0,safety:50,risk:35,lost:0,compromised:false,responded:false,warned:false,evidence:0,confirmed:false,strengths:[],improvements:[]};
const stages=[
{title:"Перше повідомлення",copy:"Артем просить 4 200 грн на картку сестри. Каже, що сам не може говорити, бо «сидить на важливій парі».",choices:[
{label:"Зателефонувати Артему за збереженим номером",hint:"Не через кнопку виклику в месенджері, а за номером, який був у вас раніше.",apply:s=>{s.verification+=35;s.safety+=15;s.risk-=20;},outcomeTitle:"Інший канал порушив сценарій шахрая",outcome:"Дзвінок не залежить від доступу до зламаного акаунта. Якщо Артем не відповість, це ще не причина переказувати гроші.",strength:"Особу перевірено незалежним каналом зв’язку."},
{label:"Запитати в чаті, що сталося",hint:"Відповідь надійде з того самого акаунта.",apply:s=>{s.verification+=8;s.risk+=5;},outcomeTitle:"Більше деталей не означає більше доказів",outcome:"Людина, яка контролює акаунт, може бачити старі повідомлення й підтримувати правдоподібну розмову.",improvement:"Не вважати листування в зламаному акаунті перевіркою особи."},
{label:"Одразу переказати 4 200 грн",hint:"Ви довіряєте знайомому фото та історії листування.",apply:s=>{s.money-=4200;s.lost+=4200;s.safety-=20;s.risk+=35;},outcomeTitle:"Гроші пішли на чужу картку",outcome:"Банк виконав ваш добровільно підтверджений переказ. Знайоме ім’я акаунта не підтвердило, хто саме писав.",improvement:"Не переказувати кошти до незалежної перевірки людини та реквізитів."}
]},
{title:"Тиск посилюється",copy:"У відповідь приходить: «Будь ласка, нікому не дзвони. Там особиста ситуація. Просто допоможи зараз». Аватар і стиль повідомлень схожі на Артема.",choices:[
{label:"Написати Артему в іншій соцмережі або зателефонувати його близькому",hint:"Використати контакт, якого немає в цьому повідомленні.",apply:s=>{s.verification+=35;s.safety+=15;s.risk-=20;},outcomeTitle:"Незалежне підтвердження дало відповідь",outcome:"Інший канал показує, чи справді Артем просив гроші. Вимога «нікому не дзвони» стала додатковим сигналом небезпеки.",strength:"Прохання перевірено поза підозрілим листуванням."},
{label:"Попросити голосове повідомлення",hint:"Голос здається надійнішим за текст.",apply:s=>{s.verification+=10;s.risk+=5;},outcomeTitle:"Голосове повідомлення не закрило сумнів",outcome:"Шахрай може переслати старий запис, використати фрагмент із чату або згенерувати схожий голос. Це допоміжна ознака, а не достатня перевірка.",improvement:"Не покладатися лише на голосове повідомлення або відео."},
{label:"Перевірити тільки фото профілю та ім’я отримувача",hint:"Якщо все виглядає знайомо, вважати прохання справжнім.",apply:s=>{s.verification+=5;s.safety-=5;s.risk+=15;},outcomeTitle:"Зовнішні ознаки легко підробити або викрасти",outcome:"Фото профілю доступне шахраю разом з акаунтом, а ім’я власника картки не підтверджує історію про сестру.",improvement:"Не замінювати незалежний контакт перевіркою аватара чи імені картки."}
]},
{title:"Посилання для «підтвердження»",copy:"Співрозмовник надсилає посилання й пише: «Якщо переказ не проходить, підтвердь картку тут. Це сторінка банку».",choices:[
{label:"Не відкривати посилання й самостійно зайти в застосунок банку",hint:"За потреби повідомити банку про підозріле посилання через офіційний канал.",apply:s=>{s.safety+=20;s.risk-=15;},outcomeTitle:"Ви не передали керування шахрайській сторінці",outcome:"Офіційний застосунок або адреса, введена самостійно, не залежать від посилання з повідомлення.",strength:"Банківські дії виконано лише через офіційний застосунок."},
{label:"Відкрити посилання, але нічого не вводити",hint:"Подивитися, чи сторінка схожа на сайт банку.",apply:s=>{s.safety-=5;s.risk+=10;},outcomeTitle:"Схожий дизайн не підтверджує справжність сайту",outcome:"Фішингові сторінки копіюють логотипи й кольори банків. Сам перехід також може вести на небезпечний ресурс.",improvement:"Не перевіряти підозріле посилання методом «просто відкрию»."},
{label:"Ввести номер картки, строк дії, CVV і код із SMS",hint:"Сторінка обіцяє підтвердити або повернути переказ.",apply:s=>{s.compromised=true;s.safety-=30;s.risk+=45;},outcomeTitle:"Дані картки та код отримали сторонні",outcome:"CVV, PIN і коди підтвердження не можна повідомляти нікому. Тепер потрібно негайно обмежити доступ до коштів через банк.",improvement:"Ніколи не вводити платіжні дані на сторінці з отриманого посилання."}
]},
{title:"Справжній Артем виходить на зв’язок",copy:"Артем телефонує сам і каже, що його акаунт зламали. Від його імені вже написали кільком людям.",choices:[
{label:"Зберегти скриншоти, поскаржитися на акаунт і попередити групу",hint:"Передати лише потрібні докази, не поширюючи зайвих персональних даних.",apply:s=>{s.confirmed=true;s.verification=100;s.evidence+=2;s.warned=true;s.safety+=20;s.risk-=15;},outcomeTitle:"Попередження розірвало ланцюг шахрайства",outcome:"Прямий дзвінок Артема остаточно підтвердив злам. Докази допоможуть банку та правоохоронцям, а коротке попередження захистить інших одногрупників.",strength:"Шахрайство підтверджено незалежним каналом, докази збережено, а потенційних жертв попереджено."},
{label:"Видалити чат і забути про нього",hint:"Ви вже знаєте правду, тому листування начебто не потрібне.",apply:s=>{s.confirmed=true;s.verification=100;s.evidence=0;s.risk+=10;},outcomeTitle:"Особу перевірено, але разом із чатом зникла частина доказів",outcome:"Дзвінок Артема підтвердив злам, однак без скриншотів, реквізитів, часу й посилань складніше пояснити банку або Кіберполіції, що саме сталося.",improvement:"Не видаляти підозріле листування до фіксації доказів."},
{label:"Погрожувати шахраю в чаті",hint:"Спробувати змусити його зізнатися або повернути гроші.",apply:s=>{s.confirmed=true;s.verification=100;s.safety-=5;s.risk+=12;},outcomeTitle:"Злам підтверджено, але суперечка не повернула контроль",outcome:"Дзвінок Артема вже довів шахрайство. Подальша суперечка може лише спонукати шахрая видалити повідомлення, заблокувати вас або продовжити маніпуляцію.",improvement:"Не витрачати час на суперечку зі шахраєм."}
]}
];
const recoveryStage={title:"Що робити після помилки",copy:"Переказ уже здійснено або платіжні дані потрапили на підозрілу сторінку. Кожна хвилина може мати значення.",choices:[
{label:"Негайно звернутися до банку та подати заяву до Кіберполіції",hint:"Телефонувати за офіційним номером банку, заблокувати картку або доступ і передати докази.",apply:s=>{s.responded=true;s.safety+=30;s.risk-=25;},outcomeTitle:"Швидка реакція обмежила подальшу шкоду",outcome:"Повернення добровільного переказу не гарантоване, але банк може захистити решту коштів і зафіксувати звернення. Заява та докази потрібні для розслідування.",strength:"Після помилки негайно залучено банк і Кіберполіцію."},
{label:"Почекати до завтра, раптом гроші повернуть",hint:"Не блокувати картку й не повідомляти банк сьогодні.",apply:s=>{s.safety-=20;s.risk+=25;},outcomeTitle:"Очікування дало шахраю більше часу",outcome:"Якщо дані картки скомпрометовані, можуть відбутися нові операції. Чим пізніше звернення, тим складніше швидко обмежити наслідки.",improvement:"Не відкладати звернення до банку після втрати грошей або даних."},
{label:"Просити шахрая повернути кошти в тому самому чаті",hint:"Сподіватися владнати все без банку й заяви.",apply:s=>{s.safety-=15;s.risk+=20;},outcomeTitle:"Шахрай отримав можливість для другого тиску",outcome:"Вам можуть запропонувати «повернення» через нове посилання, комісію або ще один код. Це продовження схеми.",improvement:"Не платити за обіцянку повернення вже втрачених коштів."}
]};
const safeStage={title:"Як допомогти після зламу",copy:"Ви не передали гроші чи платіжні дані. Але акаунт Артема досі може становити небезпеку для інших.",choices:[
{label:"Допомогти змінити пароль, завершити чужі сеанси й увімкнути двофакторний захист",hint:"Також попередити контакти Артема про шахрайські повідомлення.",apply:s=>{s.warned=true;s.safety+=20;s.risk-=15;},outcomeTitle:"Захищено не лише ваші гроші, а й акаунт друга",outcome:"Новий унікальний пароль, вихід із невідомих пристроїв і двофакторний захист зменшують ризик повторного захоплення акаунта.",strength:"Після інциденту посилено захист акаунта та попереджено контакти."},
{label:"Опублікувати скриншот із повним номером картки",hint:"Нехай усі бачать реквізити шахрая.",apply:s=>{s.safety-=10;s.risk+=15;},outcomeTitle:"Попередження розкрило зайві дані",outcome:"Картка може належати підставній або ошуканій людині. Для попередження достатньо описати схему, а повні реквізити передати банку й правоохоронцям.",improvement:"Не публікувати повні платіжні реквізити у відкритому доступі."},
{label:"Нічого не робити, бо ви не постраждали",hint:"Нехай інші самі розпізнають підозріле прохання.",apply:s=>{s.risk+=10;},outcomeTitle:"Особисті кошти вціліли, але схема продовжилася",outcome:"Коротке попередження могло зупинити наступний переказ. Без нього шахрай і далі використовує довіру до Артема.",improvement:"Попереджати контакти людини про підтверджений злам акаунта."}
]};
let state,idx,active;
const el={intro:document.getElementById("case-intro"),start:document.getElementById("start-button"),game:document.getElementById("game"),grid:document.getElementById("game-grid"),result:document.getElementById("result"),progress:document.getElementById("progress"),step:document.getElementById("scene-step"),title:document.getElementById("scene-title"),copy:document.getElementById("scene-copy"),choices:document.getElementById("choices"),box:document.getElementById("consequence"),ct:document.getElementById("consequence-title"),cc:document.getElementById("consequence-copy"),next:document.getElementById("next-button"),restart:document.getElementById("restart-button")};
const clamp=(v,a,b)=>Math.min(b,Math.max(a,v)),money=v=>`${Math.round(v).toLocaleString("uk-UA")} грн`;
function metrics(){state.money=Math.round(state.money);state.verification=clamp(state.verification,0,100);state.safety=clamp(state.safety,0,100);if(state.lost>0||state.compromised)state.safety=Math.min(state.safety,75);state.risk=clamp(state.risk,0,100);document.getElementById("metric-money").textContent=money(state.money);document.getElementById("metric-verification").textContent=`${state.verification} / 100`;document.getElementById("metric-safety").textContent=`${state.safety} / 100`;document.getElementById("metric-risk").textContent=`${state.risk} / 100`;}
function apply(c){c.apply(state);if(c.strength&&!state.strengths.includes(c.strength))state.strengths.push(c.strength);if(c.improvement&&!state.improvements.includes(c.improvement))state.improvements.push(c.improvement);metrics();}
function render(){active=idx===4?(state.lost>0||state.compromised?recoveryStage:safeStage):stages[idx];el.progress.style.width=`${(idx+1)*20}%`;el.step.textContent=`Рішення ${idx+1} із 5`;el.title.textContent=active.title;el.copy.textContent=active.copy;el.box.classList.remove("is-visible");el.choices.innerHTML="";active.choices.forEach(c=>{const b=document.createElement("button");b.type="button";b.className="choice";b.innerHTML=`<strong>${c.label}</strong><span>${c.hint}</span>`;b.onclick=()=>choose(c,b);el.choices.appendChild(b);});metrics();el.grid.scrollIntoView({behavior:"smooth",block:"start"});}
function choose(c,b){apply(c);[...el.choices.children].forEach(x=>{x.disabled=true;x.classList.toggle("is-selected",x===b);});el.ct.textContent=c.outcomeTitle;el.cc.textContent=c.outcome;el.next.textContent=idx===4?"Побачити фінал →":"Продовжити →";el.box.classList.add("is-visible");}
function ending(){if((state.lost>0||state.compromised)&&state.responded&&state.evidence>0)return{badge:"Швидка реакція після помилки",title:"Ви не приховали проблему й обмежили подальшу шкоду",lead:"Повернення переказу не гарантоване, але негайне звернення до банку, блокування доступу, збережені докази та заява дають найкращий шанс захистити решту коштів і зафіксувати злочин."};if((state.lost>0||state.compromised)&&state.responded)return{badge:"Реакція без повних доказів",title:"Доступ захищено, але частину доказів втрачено",lead:"Ви вчасно звернулися до банку й обмежили подальшу шкоду. Проте видалене або не збережене листування може ускладнити перевірку реквізитів і розслідування."};if(state.compromised)return{badge:"Дані картки скомпрометовано",title:"Фішинг отримав доступ до платіжних даних",lead:"Не чекайте підозрілої операції. Потрібно негайно зв’язатися з банком, заблокувати картку або онлайн-доступ і змінити пов’язані паролі."};if(state.lost>0)return{badge:"Переказ шахраю",title:"Довіра до знайомого акаунта коштувала 4 200 грн",lead:"Фото, ім’я та старе листування не довели особу співрозмовника. Збережіть докази, негайно зверніться до банку та подайте заяву до Кіберполіції."};if(state.confirmed&&state.warned&&state.risk<=35)return{badge:"Шахрайство зупинено",title:"Злам підтверджено, а інших користувачів попереджено",lead:"Прямий контакт зі справжнім Артемом підтвердив шахрайство. Ви не передали гроші чи дані, зберегли докази та допомогли зупинити подальшу розсилку."};return{badge:"Неповна реакція",title:"Шахрайство підтверджено, але захист не завершено",lead:"Сумніву щодо зламу вже немає, адже справжній Артем підтвердив його незалежним дзвінком. Однак докази, попередження контактів або захист акаунта потребували більшої уваги."};}
function list(id,a,f){const u=document.getElementById(id);u.innerHTML="";const x=[...new Set(a)];(x.length?x:[f]).slice(0,4).forEach(t=>{const l=document.createElement("li");l.textContent=t;u.appendChild(l);});}
function result(){const e=ending();el.grid.style.display="none";el.result.classList.add("is-visible");document.getElementById("result-badge").textContent=e.badge;document.getElementById("result-title").textContent=e.title;document.getElementById("result-lead").textContent=e.lead;document.getElementById("result-money").textContent=money(state.money);document.getElementById("result-verification").textContent=`${state.verification} / 100`;document.getElementById("result-safety").textContent=`${state.safety} / 100`;document.getElementById("result-risk").textContent=`${state.risk} / 100`;list("result-strengths",state.strengths,"Ви завершили сценарій і можете перевірити іншу модель.");list("result-improvements",state.improvements,"Завжди перевіряйте термінові прохання іншим каналом.");el.result.scrollIntoView({behavior:"smooth",block:"start"});}
function start(){state={...initialState,strengths:[],improvements:[]};idx=0;el.intro.style.display="none";el.game.classList.add("is-visible");el.grid.style.display="";el.result.classList.remove("is-visible");render();}
el.start.onclick=start;el.next.onclick=()=>{if(idx===4)return result();idx++;render();};el.restart.onclick=start;
