const initialState={personal:11000,reserve:0,debt:0,owed:0,trust:60,risk:30,extraBurden:0,contributionModel:"none",departingContribution:0,resolved:false,strengths:[],improvements:[]};
const stages=[
{title:"Як ділити 24 000 грн",copy:"Першого вечора потрібно визначити внески за оренду, комунальні послуги та інтернет. Доходи різні, але кімнатами всі користуються однаково.",choices:[
{label:"По 8 500 грн із кожного",hint:"24 000 грн на рахунки та 1 500 грн у спільний резерв.",apply:s=>{s.personal-=8500;s.reserve+=1500;s.contributionModel="equal_with_reserve";s.departingContribution=8500;s.trust+=12;s.risk-=10;},outcomeTitle:"Просте правило створило невеликий запас",outcome:"Внески рівні й зрозумілі, але для Оксани 8 500 грн становлять майже весь дохід. Домовленість варто переглядати, якщо така модель не витримується.",strength:"Суму внеску, строк і призначення резерву погоджено наперед."},
{label:"Платити рівно по 8 000 грн без письмових правил",hint:"Рахунки закриті, але резерву й плану на зміни немає.",apply:s=>{s.personal-=8000;s.contributionModel="equal";s.departingContribution=8000;s.trust-=5;s.risk+=12;},outcomeTitle:"Цей місяць закрито, наступний лишився без правил",outcome:"Рівний поділ спрацював лише для відомої суми. Не визначено, що робити зі зміною комунальних платежів, боргами або виїздом.",improvement:"Фіксувати не лише суму, а й правила для змін та винятків."},
{label:"Розподілити внески з урахуванням доходів",hint:"Ви - 8 000 грн, Оксана - 6 500 грн, Максим - 11 000 грн; 1 500 грн лишаються в резерві.",apply:s=>{s.personal-=8000;s.reserve+=1500;s.contributionModel="proportional";s.departingContribution=11000;s.trust+=15;s.risk-=8;},outcomeTitle:"Нерівні внески дали рівніший фінансовий тиск",outcome:"Кожен сплачує різну суму за погодженим принципом. Модель складніша, зате Оксана не віддає майже весь дохід.",strength:"Внески погоджено з урахуванням різних доходів."}
]},
{title:"Хто купує продукти",copy:"На перший спільний тиждень потрібно 6 000 грн. У кожного різний режим харчування, а Максим пропонує: «Ти купи зараз, потім розрахуємося».",choices:[
{label:"Заплатити всі 6 000 грн самостійно",hint:"Друзі повернуть по 2 000 грн без конкретної дати.",apply:s=>{s.personal-=6000;s.owed+=4000;s.trust-=12;s.risk+=18;},outcomeTitle:"Спільна покупка стала вашим кредитом друзям",outcome:"Сума й строк повернення не зафіксовані. Навіть добрі наміри легко губляться серед наступних витрат.",improvement:"Не фінансувати спільні покупки без суми та строку повернення."},
{label:"Скласти список і внести по 2 000 грн до покупки",hint:"Спільні продукти окремо, особисті кожен купує сам.",apply:s=>{s.personal-=2000;s.trust+=14;s.risk-=10;},outcomeTitle:"Список прибрав суперечки про чужі покупки",outcome:"Базові продукти купуються зі спільних коштів, а індивідуальні бажання не оплачують усі мешканці.",strength:"Спільні та особисті продукти розділено до покупки."},
{label:"Нехай кожен купує все окремо",hint:"Просто, але частина продуктів і побутових речей дублюватиметься.",apply:s=>{s.personal-=2500;s.trust-=3;s.risk+=3;},outcomeTitle:"Борги не виникли, але економії від спільного проживання стало менше",outcome:"Модель працює, якщо всіх влаштовує. Однак молоко, олія, засоби для прибирання й доставка можуть оплачуватися кілька разів.",strength:"Особисті витрати не створили боргів між мешканцями.",improvement:"Залишити хоча б короткий список справді спільних покупок."}
]},
{title:"Комунальний рахунок більший на 3 000 грн",copy:"Через холодний місяць рахунки зросли. Платіж потрібно зробити за три дні.",choices:[
{label:"Використати резерв, решту поділити на трьох",hint:"Якщо резерв 1 500 грн, кожен додає ще по 500 грн.",apply:s=>{const rest=Math.max(0,3000-s.reserve);s.reserve=Math.max(0,s.reserve-3000);s.personal-=Math.round(rest/3);s.trust+=10;s.risk-=8;},outcomeTitle:"Резерв пом’якшив зміну рахунку",outcome:"Несподівана сума не лягла на одну людину. Правило зрозуміле й може повторюватися наступного місяця.",strength:"Змінний рахунок покрито резервом і погодженими внесками."},
{label:"Оплатити всі 3 000 грн і попросити повернути потім",hint:"Точного строку повернення знову немає.",apply:s=>{s.personal-=3000;s.owed+=2000;s.trust-=12;s.risk+=18;},outcomeTitle:"Другий борг зробив ситуацію системною",outcome:"Ви знову закрили проблему власними коштами. Тепер складніше згадати, хто, скільки й за що має повернути.",improvement:"Не накопичувати усні борги за регулярними рахунками."},
{label:"Відкласти оплату до наступних доходів",hint:"Рахунок не зникає, а ризик прострочення зростає.",apply:s=>{s.debt+=3000;s.trust-=8;s.risk+=22;},outcomeTitle:"Відкладений рахунок став спільним боргом",outcome:"Пауза без конкретного плану не вирішила нестачу. Наступний місяць почнеться зі старого зобов’язання.",improvement:"Для відкладеного платежу одразу погоджувати джерело й дату погашення."}
]},
{title:"Один із трьох виїжджає",copy:"Максим повідомляє, що через десять днів переїжджає до іншого міста. Оренда квартири не змінюється, а нового мешканця ще немає.",choices:[
{label:"Зафіксувати дату, його платежі й разом шукати заміну",hint:"Окремо погодити повернення застави після остаточних рахунків.",apply:s=>{s.trust+=18;s.risk-=15;},outcomeTitle:"Виїзд став керованою процедурою",outcome:"Зрозуміло, хто платить до якої дати, коли перевіряються останні рахунки й за яких умов повертається частина застави.",strength:"Умови дострокового виїзду погоджено до остаточного розрахунку."},
{label:"Вимагати оплатити весь наступний місяць",hint:"Це не було погоджено під час заселення.",apply:s=>{s.trust-=25;s.risk+=20;},outcomeTitle:"Фінансова вимога перетворилася на конфлікт",outcome:"Ваше бажання зрозуміле, але правило з’явилося після рішення про виїзд. Без попередньої домовленості сторони бачать справедливість по-різному.",improvement:"Умови попередження про виїзд погоджувати під час заселення."},
{label:"Удвох мовчки покривати частку Максима",hint:"Ваше додаткове навантаження залежатиме від раніше обраної моделі внесків.",apply:s=>{const burden=s.contributionModel==="proportional"?Math.round(s.departingContribution*11000/20000):Math.round(s.departingContribution/2);s.personal-=burden;s.extraBurden+=burden;s.trust-=8;s.risk+=22;},outcomeTitle:"Відсутність конфлікту стала дорогим мовчанням",outcome:"Проблему не обговорили, тому частка Максима розподілилася за раніше обраною моделлю. Такий бюджет може не витримати другого місяця.",improvement:"Не приймати довгострокове додаткове навантаження без нового бюджету."}
]}
];
const debtStage={title:"Борги, які вже важко пам’ятати",copy:"У спільному чаті різні суми й чеки. Хтось не погоджується з підрахунком, а новий місяць уже почався.",choices:[
{label:"Звести платежі в таблицю й погодити графік повернення",hint:"Дата, сума, призначення й підтвердження кожного платежу.",apply:s=>{s.resolved=true;s.trust+=20;s.risk-=15;},outcomeTitle:"Борг став планом, а не образою",outcome:"Не все повертається одразу, але кожен бачить однакові цифри та строки.",strength:"Борги звірено за чеками й переведено в погоджений графік."},
{label:"Не згадувати про гроші, щоб не псувати дружбу",hint:"Сума лишається неврегульованою.",apply:s=>{s.trust-=12;s.risk+=12;},outcomeTitle:"Мовчання не списало борг",outcome:"Фінансове питання переходить у приховану образу й впливатиме на наступні спільні рішення.",improvement:"Не замінювати фінансову домовленість мовчанням."},
{label:"Вимагати все негайно в загальному чаті",hint:"Без попередньої звірки чеків і сум.",apply:s=>{s.trust-=25;s.risk+=18;},outcomeTitle:"Право на повернення грошей загубилося в конфлікті",outcome:"Емоційна вимога не пояснює розрахунок. Частина боргу оскаржується, а домовитися стає складніше.",improvement:"Спочатку звіряти факти, потім погоджувати строк повернення."}
]};
const stableStage={title:"Спільна покупка для квартири",copy:"Після основних платежів мешканці хочуть купити пилосос за 6 000 грн. Потрібно визначити, кому він належатиме після виїзду.",choices:[
{label:"Відкласти покупку до появи нового мешканця",hint:"Спочатку стабілізувати склад і бюджет.",apply:s=>{s.trust+=8;s.risk-=10;},outcomeTitle:"Пауза захистила спільний бюджет",outcome:"Необов’язкова покупка не випередила важливіші витрати й нові домовленості.",strength:"Велика спільна покупка відкладена до стабілізації бюджету."},
{label:"Один купує й залишається власником",hint:"Інші не сплачують частку, але користуються за домовленістю.",apply:s=>{s.personal-=6000;s.trust+=5;s.risk-=3;},outcomeTitle:"Власник визначений до оплати",outcome:"Під час майбутнього виїзду не доведеться ділити річ або повертати внески.",strength:"Право власності на спільно використовувану річ погоджено наперед."},
{label:"Взяти гроші з фонду комунальних платежів",hint:"Рахунки ще можуть змінитися.",apply:s=>{s.reserve-=6000;s.debt+=Math.max(0,-s.reserve);s.reserve=Math.max(0,s.reserve);s.trust-=15;s.risk+=22;},outcomeTitle:"Необов’язкова річ витіснила обов’язкові платежі",outcome:"Пилосос з’явився, але фонд рахунків утратив своє призначення.",improvement:"Не використовувати гроші обов’язкових платежів на необов’язкові покупки."}
]};
let state,idx,active;const el={intro:document.getElementById("case-intro"),start:document.getElementById("start-button"),game:document.getElementById("game"),grid:document.getElementById("game-grid"),result:document.getElementById("result"),progress:document.getElementById("progress"),step:document.getElementById("scene-step"),title:document.getElementById("scene-title"),copy:document.getElementById("scene-copy"),choices:document.getElementById("choices"),box:document.getElementById("consequence"),ct:document.getElementById("consequence-title"),cc:document.getElementById("consequence-copy"),next:document.getElementById("next-button"),restart:document.getElementById("restart-button")};
const clamp=(v,a,b)=>Math.min(b,Math.max(a,v)),money=v=>`${Math.round(v).toLocaleString("uk-UA")} грн`;
function metrics(){state.personal=Math.round(state.personal);state.reserve=Math.max(0,Math.round(state.reserve));state.trust=clamp(state.trust,0,100);state.risk=clamp(state.risk,0,100);document.getElementById("metric-personal").textContent=money(state.personal);document.getElementById("metric-reserve").textContent=money(state.reserve);document.getElementById("metric-debt").textContent=money(state.debt+state.owed);document.getElementById("metric-trust").textContent=`${state.trust} / 100`;}
function apply(c){c.apply(state);if(c.strength&&!state.strengths.includes(c.strength))state.strengths.push(c.strength);if(c.improvement&&!state.improvements.includes(c.improvement))state.improvements.push(c.improvement);metrics();}
function render(){active=idx===4?(state.debt>0||state.owed>0?debtStage:stableStage):stages[idx];el.progress.style.width=`${(idx+1)*20}%`;el.step.textContent=`Рішення ${idx+1} із 5`;el.title.textContent=active.title;el.copy.textContent=active.copy;el.box.classList.remove("is-visible");el.choices.innerHTML="";active.choices.forEach((c,i)=>{const b=document.createElement("button");b.type="button";b.className="choice";b.innerHTML=`<strong>${c.label}</strong><span>${c.hint}</span>`;b.onclick=()=>choose(c,b);el.choices.appendChild(b);});metrics();el.grid.scrollIntoView({behavior:"smooth",block:"start"});}
function choose(c,b){apply(c);[...el.choices.children].forEach(x=>{x.disabled=true;x.classList.toggle("is-selected",x===b);});el.ct.textContent=c.outcomeTitle;el.cc.textContent=c.outcome;el.next.textContent=idx===4?"Побачити фінал →":"Продовжити →";el.box.classList.add("is-visible");}
function ending(){if(state.trust<35||state.risk>=80)return{badge:"Фінансовий конфлікт",title:"Нечіткі правила зіпсували і бюджет, і стосунки",lead:"Проблема не в одній покупці, а у відсутності спільних цифр, строків і правил для винятків."};if(state.owed>=4000&&!state.resolved)return{badge:"Ви стали спонсором квартири",title:"Спільні витрати непомітно перейшли на одну людину",lead:"Регулярна оплата за інших виснажує особистий бюджет і накопичує образу, навіть якщо друзі щиро планують повернути кошти."};if(state.personal<0||state.extraBurden>=4000)return{badge:"Бюджет не витримав",title:"Чужа частка стала вашим постійним навантаженням",lead:"Спільні витрати перевищили ваші можливості. Потрібно переглянути житло, склад мешканців або модель внесків."};if((state.debt>0||state.owed>0)&&state.resolved)return{badge:"Борги під контролем",title:"Ви повернули спільним грошам точні цифри",lead:"Борг не зник, але має підтверджену суму, відповідального та строк. Це реалістичніше за обіцянку «потім розрахуємося»."};if(state.debt===0&&state.trust>=75&&state.risk<=30)return{badge:"Стійка домовленість",title:"Спільний бюджет працює без спільного гаманця",lead:"Кожен зберігає особисті кошти, але правила базових витрат, резерву та змін однаково зрозумілі всім."};return{badge:"Крихкий баланс",title:"Цей місяць оплачено, але правила ще не витримали перевірку",lead:"Варто зафіксувати борги, змінні платежі й умови виїзду до наступної несподіваної ситуації."};}
function list(id,a,f){const u=document.getElementById(id);u.innerHTML="";const x=[...new Set(a)];(x.length?x:[f]).slice(0,4).forEach(t=>{const l=document.createElement("li");l.textContent=t;u.appendChild(l);});}
function result(){const e=ending();el.grid.style.display="none";el.result.classList.add("is-visible");document.getElementById("result-badge").textContent=e.badge;document.getElementById("result-title").textContent=e.title;document.getElementById("result-lead").textContent=e.lead;document.getElementById("result-personal").textContent=money(state.personal);document.getElementById("result-reserve").textContent=money(state.reserve);document.getElementById("result-debt").textContent=money(state.debt+state.owed);document.getElementById("result-trust").textContent=`${state.trust} / 100`;list("result-strengths",state.strengths,"Ви завершили сценарій і можете перевірити іншу модель.");list("result-improvements",state.improvements,"Зафіксуйте правила спільних витрат до наступного платежу.");el.result.scrollIntoView({behavior:"smooth",block:"start"});}
function start(){state={...initialState,strengths:[],improvements:[]};idx=0;el.intro.style.display="none";el.game.classList.add("is-visible");el.grid.style.display="";el.result.classList.remove("is-visible");render();}el.start.onclick=start;el.next.onclick=()=>{if(idx===4)return result();idx++;render();};el.restart.onclick=start;
