const evidence=[
{id:'promise',type:'Реклама',title:'«20% щомісяця гарантовано»',preview:'Висока дохідність · «ризику немає»',visual:'РЕКЛАМНА СТОРІНКА\n\nNovaYield\n20% щомісяця\nГарантований прибуток\nРизик: 0%',copy:'Формулювання поєднує надзвичайно високу стабільну дохідність із твердженням про відсутність ризику. Це сильний сигнал для додаткової перевірки.',key:true,icon:'20%'},
{id:'chat',type:'Чат знайомого',title:'«Мій друг уже отримав виплату»',preview:'Один приватний досвід',visual:'ЧАТ\n\n«Друг вклав 10 000 грн і вже отримав першу виплату. Значить усе працює».',copy:'Окрема виплата не доводить стійкість або законність моделі. Пірамідальні схеми теж можуть певний час платити раннім учасникам.',key:false,icon:'?'},
{id:'referral',type:'Бонусна програма',title:'10% за нового вкладника',preview:'Винагорода за залучення людей',visual:'ПАРТНЕРСЬКА ПРОГРАМА\n\nЗапросіть нового учасника — отримайте 10% від суми його першого внеску.',copy:'Винагорода, прямо прив’язана до нових внесків, важлива для перевірки того, чи не залежать виплати від постійного притоку нових грошей.',key:true,icon:'+1'},
{id:'logo',type:'Дизайн платформи',title:'Професійний логотип і мобільний застосунок',preview:'Якісний вигляд інтерфейсу',visual:'ЗАСТОСУНОК\n\nNovaYield\nБаланс · графік · зелена стрілка\nПреміальний дизайн',copy:'Професійний дизайн не є доказом надійності інвестиційної моделі або наявності реальних активів.',key:false,icon:'APP'},
{id:'withdrawal',type:'Умови виведення',title:'Основна сума заблокована на 180 днів',preview:'Дострокове повернення не гарантується',visual:'УМОВИ\n\nСтрок: 180 днів\nДострокове виведення: за рішенням платформи\nГарантія повернення: відсутня',copy:'Обмежена ліквідність означає, що інвестор не може вільно повернути гроші, коли вони потрібні.',key:true,icon:'180'},
{id:'source',type:'Опис стратегії',title:'«Секретний торговий алгоритм»',preview:'Без активів, звітності та методики',visual:'ЯК МИ ЗАРОБЛЯЄМО\n\n«Наш секретний AI-алгоритм генерує прибуток на глобальних ринках».\n\nПерелік активів: немає\nАудит: немає\nМетодика: не розкривається',copy:'Немає перевірюваного пояснення, звідки формується дохід і які ризики бере на себе платформа.',key:true,icon:'AI'},
{id:'celebrity',type:'Публікація в соцмережі',title:'Фото відомого блогера поруч із логотипом',preview:'Без підтвердженої рекомендації',visual:'СОЦМЕРЕЖА\n\nФото блогера + логотип NovaYield\nПідпис: «Успіх любить сміливих»',copy:'Зображення чи натяк на підтримку відомої людини не замінює перевірку юридичних та фінансових фактів.',key:false,icon:'★'},
{id:'documents',type:'Документи компанії',title:'Немає договору з описом ризиків і активів',preview:'Лише правила сайту · без фінансової звітності',visual:'РОЗДІЛ ДОКУМЕНТІВ\n\nУмови користування: є\nДоговір інвестування: немає\nПерелік активів: немає\nПеревірена звітність: немає',copy:'Відсутність документів, що описують права інвестора, активи, ризики та порядок повернення коштів, є ключовою прогалиною.',key:true,icon:'DOC'}
];
const assessments=[
{id:'a',label:'Висновок А',text:'Якщо платформа обіцяє фіксовані 20% щомісяця, це автоматично означає безпечний депозит.',correct:false},
{id:'b',label:'Висновок Б',text:'Пропозиція має високий ризик: надприбуток без поясненого джерела, обмежене виведення та бонуси за нових учасників вимагають відмови від переказу до повної перевірки.',correct:true},
{id:'c',label:'Висновок В',text:'Достатньо перевірити, чи красиво зроблений застосунок і чи є позитивні коментарі.',correct:false},
{id:'d',label:'Висновок Г',text:'Якщо перші учасники отримують виплати, ризик повної втрати коштів відсутній.',correct:false}
];
const suspects=[
{id:'deposit',mark:'01',title:'Звичайний банківський депозит',text:'Для депозиту характерні зрозумілі умови, ставка, договір та визначений порядок повернення. Матеріали справи цього не показують.',correct:false},
{id:'pyramid',mark:'02',title:'Пірамідальна модель',text:'Бонуси за нові внески, непрозоре джерело прибутку й затримка виведення узгоджуються з моделлю, де виплати залежать від постійного притоку нових грошей.',correct:true},
{id:'discount',mark:'03',title:'Звичайна рекламна акція',text:'Рекламні бонуси не пояснюють відсутність активів, надприбуток і обмеження повернення основної суми.',correct:false},
{id:'inflation',mark:'04',title:'Захист від інфляції',text:'Інфляція не створює механізм, за яким можна гарантовано платити 20% щомісяця.',correct:false}
];
const plans=[
{id:'source',mark:'01',title:'Перевірити джерело доходу та активи',text:'Зрозуміти, у що саме вкладаються гроші, як формується прибуток і які ризики існують.',correct:true},
{id:'rush',mark:'02',title:'Переказати невелику суму, поки діє бонус',text:'Тиск терміновості не замінює перевірку. Навіть невеликий перший внесок може затягнути в схему.',correct:false},
{id:'legal',mark:'03',title:'Перевірити юридичні дані та умови договору',text:'Потрібно бачити, хто приймає гроші, які права має інвестор і як оформлюється повернення коштів.',correct:true},
{id:'liquidity',mark:'04',title:'Оцінити ліквідність і сценарій повної втрати',text:'Перед інвестуванням треба знати, коли можна повернути гроші і чи витримає особистий бюджет повну втрату цієї суми.',correct:true},
{id:'friends',mark:'05',title:'Орієнтуватися на виплати друзям',text:'Чужий позитивний досвід не доводить стійкість схеми та не замінює аналіз документів.',correct:false},
{id:'compare',mark:'06',title:'Порівняти дохідність із ризиком і альтернативами',text:'Чим вища обіцяна дохідність, тим переконливішими мають бути пояснення ризику, активів і механізму прибутку.',correct:true}
];
const state={viewed:new Set(),selected:new Set(),assessment:null,suspect:null,plans:new Set(),evidenceScore:0,assessmentScore:0,verdictScore:0,planScore:0,currentEvidence:null};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
function renderEvidence(){const cards=evidence.map((x,i)=>`<button class="evidence-card" data-evidence="${x.id}" type="button"><span class="evidence-top"><span>МАТЕРІАЛ ${String(i+1).padStart(2,'0')}</span><b class="evidence-state">Не оглянуто</b></span><span class="evidence-icon">${x.icon}</span><span class="evidence-type">${x.type}</span><strong>${x.title}</strong><small>${x.preview}</small><em>Відкрити документ →</em></button>`).join('');$('#evidence-board').innerHTML=`<header class="board-toolbar"><div><span>ІНВЕСТИЦІЙНІ СЛІДИ · CB-88021</span><strong>Матеріали пропозиції</strong></div><div><small>Оглянуто</small><b id="board-viewed">0 / 8</b></div></header><div class="board-canvas">${cards}</div><section class="selection-folder"><header><div><span>РОБОЧА ПАПКА</span><strong>Ключові докази ризику</strong></div><small>Рівно 5 матеріалів</small></header><ol id="selected-evidence"></ol></section>`}
function renderChoices(){$('#assessment-options').innerHTML=assessments.map(x=>`<button class="choice-option" data-assessment="${x.id}" type="button"><span class="option-mark">${x.label.slice(-1)}</span><span><strong>${x.label}</strong><small>${x.text}</small></span></button>`).join('');$('#suspects').innerHTML=suspects.map(x=>`<button class="choice-option" data-suspect="${x.id}" type="button"><span class="option-mark">${x.mark}</span><span><strong>${x.title}</strong><small>${x.text}</small></span></button>`).join('');$('#plan-options').innerHTML=plans.map(x=>`<button class="choice-option" data-plan="${x.id}" type="button"><span class="option-mark">${x.mark}</span><span><strong>${x.title}</strong><small>${x.text}</small></span></button>`).join('')}
function updateDashboard(stage=1){$('#dash-stage').textContent=`${stage} / 4`;$('#dash-viewed').textContent=`${state.viewed.size} / 8`;$('#dash-selected').textContent=`${state.selected.size} / 5`;const earned=state.evidenceScore+state.assessmentScore+state.verdictScore+state.planScore;const available=[0,40,60,80,100][stage];$('#dash-score').textContent=`${Math.round(earned/available*100)||0}%`}
function openEvidence(id){const x=evidence.find(e=>e.id===id);state.currentEvidence=id;state.viewed.add(id);$('#modal-label').textContent=`Матеріал справи · ${x.type}`;$('#modal-title').textContent=x.title;$('#modal-visual').textContent=x.visual;$('#modal-copy').textContent=x.copy;updateEvidence();updateModalButton();$('#evidence-modal').hidden=false;document.body.classList.add('modal-open')}
function closeModal(){$('#evidence-modal').hidden=true;document.body.classList.remove('modal-open');state.currentEvidence=null}
function updateModalButton(){const yes=state.selected.has(state.currentEvidence);$('#modal-select').textContent=yes?'Вилучити з робочої папки':'Долучити до робочої папки';$('#modal-select').classList.toggle('is-remove',yes)}
function toggleEvidence(){const id=state.currentEvidence;if(state.selected.has(id))state.selected.delete(id);else if(state.selected.size<5)state.selected.add(id);updateModalButton();updateEvidence()}
function updateEvidence(){$$('.evidence-card').forEach(card=>{const id=card.dataset.evidence,viewed=state.viewed.has(id),selected=state.selected.has(id);card.classList.toggle('is-viewed',viewed);card.classList.toggle('is-selected',selected);card.querySelector('.evidence-state').textContent=selected?'Долучено':viewed?'Оглянуто':'Не оглянуто'});$('#board-viewed').textContent=`${state.viewed.size} / 8`;const chosen=[...state.selected].map(id=>evidence.find(x=>x.id===id));$('#selected-evidence').innerHTML=Array.from({length:5},(_,i)=>chosen[i]?`<li class="is-filled"><span>${i+1}</span><strong>${chosen[i].title}</strong><button type="button" data-remove="${chosen[i].id}" aria-label="Вилучити ${chosen[i].title}">×</button></li>`:`<li><span>${i+1}</span><em>Вільне місце для доказу</em></li>`).join('');const all=state.viewed.size===8,full=state.selected.size===5;$('#check-evidence').disabled=!(all&&full);$('#evidence-hint').textContent=!all?`Оглянуто ${state.viewed.size} із 8 матеріалів.`:!full?`Долучено ${state.selected.size} із 5 доказів.`:'Усі матеріали оглянуто. Можна зафіксувати докази.';updateDashboard(1)}
function showStage(id,number){$$('.stage').forEach(x=>x.classList.remove('is-active'));$(id).classList.add('is-active');updateDashboard(number);window.scrollTo({top:$(id).offsetTop-90,behavior:'smooth'})}
function chooseOne(selector,key,id,button){state[key]=id;$$(selector).forEach(x=>x.classList.remove('is-selected'));button.classList.add('is-selected')}
function checkEvidence(){const keys=evidence.filter(x=>x.key).map(x=>x.id);state.evidenceScore=keys.filter(x=>state.selected.has(x)).length*8;showStage('#stage-assessment',2)}
function checkAssessment(){state.assessmentScore=assessments.find(x=>x.id===state.assessment)?.correct?20:0;showStage('#stage-verdict',3)}
function checkVerdict(){state.verdictScore=suspects.find(x=>x.id===state.suspect)?.correct?20:0;showStage('#stage-plan',4)}
function togglePlan(id,button){if(state.plans.has(id)){state.plans.delete(id);button.classList.remove('is-selected')}else if(state.plans.size<4){state.plans.add(id);button.classList.add('is-selected')}$('#finish-button').disabled=state.plans.size!==4;$('#plan-hint').textContent=`Обрано ${state.plans.size} із 4 дій.`}
function finish(){state.planScore=plans.filter(x=>x.correct&&state.plans.has(x.id)).length*5;const score=state.evidenceScore+state.assessmentScore+state.verdictScore+state.planScore;$('#stage-plan').classList.remove('is-active');$('.case-dashboard').style.display='none';$('#result').classList.add('is-visible');$('#result-score').textContent=`${score} / 100`;const level=score>=90?['Ризик пропозиції встановлено','Ви правильно перевірили сигнали ризику, механізм виплат і дії до інвестування.']:score>=70?['Основна схема розкрита','Ключові ризики знайдено, але в частині доказів або протоколу залишилися неточності.']:['У справі залишилися прогалини','Поверніться до обіцянки доходу, джерела прибутку, умов виведення, реферальної програми й документів.'];$('#result-title').textContent=level[0];$('#result-lead').textContent=level[1];const missed=evidence.filter(x=>x.key&&!state.selected.has(x.id)).map(x=>x.title),noise=evidence.filter(x=>!x.key&&state.selected.has(x.id)).map(x=>x.title),wrong=plans.filter(x=>!x.correct&&state.plans.has(x.id)).map(x=>x.title);$('#report-content').innerHTML=`<p><strong>Докази:</strong> ${state.evidenceScore===40?'усі п’ять ключових матеріалів визначено правильно.':`пропущено: ${missed.join(', ')||'немає'}; зайві: ${noise.join(', ')||'немає'}.`}</p><p><strong>Оцінка:</strong> ${state.assessmentScore?'правильно враховано надприбуток, непрозоре джерело доходу та низьку ліквідність.':'оцінка не враховує сукупність ключових ризиків.'}</p><p><strong>Механізм:</strong> ${state.verdictScore?'встановлено ознаки пірамідальної моделі, залежної від нових внесків.':'обраний механізм не пояснює реферальні виплати та непрозорий дохід.'}</p><p><strong>Протокол:</strong> ${state.planScore===20?'усі чотири дії перевірки обрано правильно.':`ризикові рішення: ${wrong.join(', ')||'частину необхідних дій не обрано'}.`}</p>`;window.scrollTo({top:$('#result').offsetTop-30,behavior:'smooth'})}
function reset(){state.viewed.clear();state.selected.clear();state.plans.clear();state.assessment=null;state.suspect=null;state.evidenceScore=state.assessmentScore=state.verdictScore=state.planScore=0;$('.case-dashboard').style.display='grid';$('#result').classList.remove('is-visible');$$('.is-selected,.is-viewed').forEach(x=>x.classList.remove('is-selected','is-viewed'));$('#check-assessment').disabled=true;$('#check-verdict').disabled=true;$('#finish-button').disabled=true;$('#plan-hint').textContent='Оберіть 4 дії.';showStage('#stage-evidence',1);updateEvidence()}
renderEvidence();renderChoices();
$('#start-button').addEventListener('click',()=>{$('#investigation').classList.add('is-visible');$('#briefing').style.display='none';window.scrollTo({top:$('#investigation').offsetTop-20,behavior:'smooth'})});
$('#evidence-board').addEventListener('click',e=>{const remove=e.target.closest('[data-remove]');if(remove){state.selected.delete(remove.dataset.remove);updateEvidence();return}const card=e.target.closest('[data-evidence]');if(card)openEvidence(card.dataset.evidence)});
$('#modal-select').addEventListener('click',toggleEvidence);$$('[data-close-modal]').forEach(x=>x.addEventListener('click',closeModal));document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!$('#evidence-modal').hidden)closeModal()});
$('#check-evidence').addEventListener('click',checkEvidence);
$('#assessment-options').addEventListener('click',e=>{const b=e.target.closest('[data-assessment]');if(!b)return;chooseOne('.choice-option[data-assessment]','assessment',b.dataset.assessment,b);$('#check-assessment').disabled=false});$('#check-assessment').addEventListener('click',checkAssessment);
$('#suspects').addEventListener('click',e=>{const b=e.target.closest('[data-suspect]');if(!b)return;chooseOne('.choice-option[data-suspect]','suspect',b.dataset.suspect,b);$('#check-verdict').disabled=false});$('#check-verdict').addEventListener('click',checkVerdict);
$('#plan-options').addEventListener('click',e=>{const b=e.target.closest('[data-plan]');if(b)togglePlan(b.dataset.plan,b)});$('#finish-button').addEventListener('click',finish);$('#restart-button').addEventListener('click',reset);